### PR TITLE
Only combine when not collocated. 

### LINKED ISSUE #64: Race condition in test_dist_combine_racecondition
@ionelmc Looks like your `test_dist_combine_racecondition` has a race condition: https://travis-ci.org/schlamar/pytest-cov/jobs/70355353

### PR DESCRIPTION
**Pull request by ionelmc**
Fixes regression introduced in 8a17ab71b2a925169cb8058361ddf5bef88d217d. Fixes #64 (I hope :grin:)

### CODE REVIEW

**Comment by ionelmc** [comment]
Lets see how this goes, looks stable locally (still running tho) ...

**Comment by ionelmc** [comment]
Also, feel free to restart the build on Travis a couple times, just to be sure...

**Comment by schlamar** [comment]
Still flaky, this time on AppVeyor...

**Comment by schlamar** [comment]
Regression is tracked in #69

**Pull request merged**
